#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 2 ]]; then
  cat <<USAGE
Usage: $0 <repo_path> <prompt> [--commit-and-push]

Example:
  $0 /path/to/repo "Write a complete and beautiful README" --commit-and-push
USAGE
  exit 1
fi

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_path="$1"
user_prompt="$2"
commit_and_push="${3:-}"

if [[ ! -d "$repo_path" ]]; then
  echo "Repo path does not exist: $repo_path"
  exit 1
fi

if [[ ! -d "$repo_path/.git" ]]; then
  echo "Repo is not a git repository: $repo_path"
  exit 1
fi

auto_dir="$script_dir/auto-readme"
structure_tool="$auto_dir/auto-file-structure.sh"
write_tool="$auto_dir/auto-write-readme.sh"
beautify_tool="$auto_dir/auto-beautify.sh"
translate_tool="$auto_dir/auto-translate-readme.sh"

for f in "$structure_tool" "$write_tool" "$beautify_tool" "$translate_tool"; do
  if [[ ! -x "$f" ]]; then
    echo "Required executable missing: $f"
    exit 1
  fi
done

run_ts="$(date +%Y%m%d_%H%M%S)"
work_dir="$repo_path/.auto-readme-work/$run_ts"
mkdir -p "$work_dir"

readme_path="$repo_path/README.md"
structure_output_file="$work_dir/repo-structure-analysis.md"
pipeline_context_file="$work_dir/pipeline-context.md"
translation_plan_file="$work_dir/translation-plan.txt"

cat > "$pipeline_context_file" <<CTX
# Auto README Pipeline Context

- Run timestamp: $run_ts
- Repository path: $repo_path
- User prompt: $user_prompt
- Goal: Generate a complete, beautiful, multilingual README set.

## Step Overview
1. Analyze repository structure.
2. Create first complete README draft.
3. Beautify README with better visuals (emoji/table/badges).
4. Generate multilingual README variants.
5. Optionally commit and push changes.

## Redundant Context Notes
- Every codex step should re-read repository files and this context file.
- Each step must remain self-contained and not depend on prior session memory.
CTX

cat > "$translation_plan_file" <<'TPLAN'
en|English|README.en.md
zh-TW|Chinese Traditional|README.zh-TW.md
zh-CN|Chinese Simplified|README.zh-CN.md
ja|Japanese|README.ja.md
ko|Korean|README.ko.md
vi|Vietnamese|README.vi.md
ar|Arabic|README.ar.md
fr|French|README.fr.md
es|Spanish|README.es.md
de|Deutsch|README.de.md
ru|Russian|README.ru.md
TPLAN

language_nav_line='English | 中文繁體 | 中文简体 | 日本語 | 한국어 | Tiếng Việt | العربية | Français | Español | Deutsch | Русский'

echo "[1/5] Analyze repository structure"
"$structure_tool" "$repo_path" "$user_prompt" "$pipeline_context_file" "$structure_output_file"

echo "[2/5] Write first complete README"
"$write_tool" "$repo_path" "$user_prompt" "$pipeline_context_file" "$structure_output_file" "$readme_path"

echo "[3/5] Beautify README"
"$beautify_tool" "$repo_path" "$user_prompt" "$pipeline_context_file" "$readme_path"

echo "[4/5] Generate multilingual READMEs"
while IFS='|' read -r lang_code lang_label output_name; do
  output_path="$repo_path/$output_name"
  step_note="Translating README into $lang_label ($lang_code) as part of multilingual batch generation."
  "$translate_tool" \
    "$repo_path" \
    "$user_prompt" \
    "$pipeline_context_file" \
    "$readme_path" \
    "$lang_label" \
    "$lang_code" \
    "$output_path" \
    "$language_nav_line" \
    "$step_note"
done < "$translation_plan_file"

echo "[5/5] Optional commit and push"
if [[ "$commit_and_push" == "--commit-and-push" ]]; then
  (
    cd "$repo_path"
    git add README.md README.*.md .auto-readme-work
    if git diff --cached --quiet; then
      echo "No README changes to commit."
    else
      git commit -m "Add autogenerated multilingual README pipeline output"
      git push
    fi
  )
else
  echo "Skipping commit/push. Pass --commit-and-push to enable."
fi

echo "Pipeline completed. Work dir: $work_dir"
